[llm]
provider = "deepseek"
model_name = "deepseek-chat"

[github]
api_base_url = "https://api.github.com"

[gitee]
api_base_url = "https://gitee.com/api/v5"

[review]
types = ["code_quality", "security", "best_practices"]
max_files_per_review = 10
