[llm]
#provider = "deepseek"
#model_name = "deepseek-chat"
#base_url = ""

#provider = "ollama"
#model_name = "deepseek-r1:32b"
#base_url = "http://192.168.220.15:11434"

provider = "openai"
model_name = "qwen-plus"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"

[github]
api_base_url = "https://api.github.com"

[gitee]
api_base_url = "https://gitee.com/api/v5"

[database]
# 数据库配置
# url = "sqlite:///./backend.db"  # SQLite
url = "mysql+pymysql://root:123456@localhost:3306/pulse_guard"
echo = false  # 是否显示 SQL 语句
